### ISSUE TITLE
glfw dependency

### ISSUE THREAD

**Issue by Sahnvour** [mesonbuild/imgui#3]
I'm trying to use this wrap with `glfw` coming from another source (it's not available yet on wrapdb), but the patch looks for `dependency('glfw3')` whereas on my system the dependency is named `glfw`.

I assume it's using `glfw3` because that's the name in wrapdb, but could it use `glfw` as a fallback or something ?

**Comment by legeana** [comment]
I can only tell for ArchLinux:

```
$ pacman -Ql glfw | grep '\.pc$'
glfw-x11 /usr/lib/pkgconfig/glfw3.pc

$ pkg-config --libs glfw3
-lglfw 

$ pkg-config --libs glfw
Package glfw was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw.pc'
to the PKG_CONFIG_PATH environment variable
Package 'glfw', required by 'virtual:world', not found
```

So it seems that the `pkgconfig` name is correct. Are you using `glfw` version 3 as a system package?

**Comment by Sahnvour** [comment]
I'm getting `glfw` from [conan](https://bintray.com/bincrafters/public-conan/glfw%3Abincrafters), exposing it via the pkgconfig generator, and the file is `glfw.pc`.

**Comment by eli-schwartz** [comment]
If conan is using something other than the official upstream pkg-config name for glfw3, then there's nothing we can do about this. Please report a bug to conan; at the very least they should provide both pkg-config names -- the correct one and the backwards-compatible conan one.
